### ISSUE TITLE
Newsletter Page

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#11]
Following pages need to be created
- newsletter
- newsletter-success

**Comment by corebean** [comment]
If we can get these pages done this week, then I can ensure the new site is switched live.
Newsletter is here on the current website - http://www.ladenfreu.de/newsletter/
Newsletter-Success is here on the current website - http://www.ladenfreu.de/newsletter/enewsletter-bestatigung/

Please copy content as best you can. Then I can make changes to the A-Records.

**Comment by bereczandor** [comment]
The content(except the logo images) is copied over. Whit the next build you will see them. The confirmation page will be accesible on domain/newsletter/enewsletter-bestatigung

the logo images we could place in an about us or similar page too..

issue remains open till we have the logo images too.

**Comment by corebean** [comment]
Was brauchst du von mir? Die Bilder?

Nur dass du weisst. Ich muss dass erst haben vor ich die domain umswitchen
kann.
