### ISSUE TITLE
Posts Information

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#13]
- Do not display the entire URL for the business, but just provide a link that says "Zur Webseite".
- Do not display the entire EMAIL for the business, but just provide a link that says "Email Senden".

**Comment by bereczandor** [comment]
Done, will be released with the next build.

**Comment by corebean** [comment]
Thank you for updating this. The "Email Senden" button works, however the "Zur WEbseite" button now defaults back to to "ladenfreu.de" instead of the businesses actual URL. If the business does not have a website/URL attached, then this button should either be hidden or the words "Keine Webseite vorhanden" should appear (and no hyperlink)
