### ISSUE TITLE
Opening Times Issue

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#15]
For some reason all the data for the Opening Times looks very odd on the Post Detail page. 

It also is NOT displayed on the "Mein Konto" page.

**Comment by russog** [comment]
more details (user 100168):
below what the web site shows:
OPENING TIMES
MONDAY
8: 0 - 17: 0
TUESDAY
8: 0 - 17: 0
WEDNESDAY
8: 0 - 17: 0
THURSDAY
8: 0 - 17: 0
FRIDAY
8: 0 - 17: 0
SATURDAY
10: 0 - 19: 0
SUNDAY
10:30 To 20:30
MONDAY
8: 0 - 17: 0
TUESDAY
8: 0 - 17: 0
WEDNESDAY
8: 0 - 17: 0
THURSDAY
8: 0 - 17: 0
FRIDAY
8: 0 - 17: 0
MONDAY
8: 0 - 8: 0
TUESDAY
8: 0 - 8: 0
WEDNESDAY
8: 0 - 8: 0
THURSDAY
8: 0 - 8: 0
FRIDAY
8: 0 - 8: 0
SATURDAY
10: 0 - 10: 0
MONDAY
10: 0 - 10: 0
MONDAY
8: 0 - 8: 0
TUESDAY
8: 0 - 8: 0
WEDNESDAY
8: 0 - 8: 0
THURSDAY
8: 0 - 8: 0
FRIDAY
8: 0 - 8: 0
SATURDAY
10: 0 - 10: 0
MONDAY
10: 0 - 10: 0
MONDAY
9: 0 - 12:30
MONDAY
14:30 - 18: 0
TUESDAY
9: 0 - 12:30
TUESDAY
14:30 - 18: 0
WEDNESDAY
9: 0 - 12:30
WEDNESDAY
14:30 - 18: 0
THURSDAY
9: 0 - 12:30
THURSDAY
14:30 - 18: 0
FRIDAY
9: 0 - 12:30
FRIDAY
14:30 - 18: 0
SATURDAY
9: 0 - 12:30

the api would show:
{
  "payLoad": {
    "id": 100168,
    "email": "kontakt@dessous-studio.net",
    "userType": "SILVER",
    "postcode": "64354",
    "company": {
      "id": 100098,
      "name": "Dessous-& Strumpf Studio Reinheim",
      "owner": "Dessous-& Strumpf Studio Reinheim",
      "address": "Darmstädter Str. 45a",
      "city": "Reinheim",
      "url": "http://www.dessous-studio.net",
      "phoneNo": "06162/85832",
      "category": {
        "id": 1,
        "name": "Coupon"
      },
      "openingHours": [
        {
          "day": "Monday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        },
        {
          "day": "Monday",
          "hourStart": 14,
          "minuteStart": 30,
          "hourEnd": 18,
          "minuteEnd": 0
        },
        {
          "day": "Tuesday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        },
        {
          "day": "Tuesday",
          "hourStart": 14,
          "minuteStart": 30,
          "hourEnd": 18,
          "minuteEnd": 0
        },
        {
          "day": "Wednesday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        },
        {
          "day": "Wednesday",
          "hourStart": 14,
          "minuteStart": 30,
          "hourEnd": 18,
          "minuteEnd": 0
        },
        {
          "day": "Thursday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        },
        {
          "day": "Thursday",
          "hourStart": 14,
          "minuteStart": 30,
          "hourEnd": 18,
          "minuteEnd": 0
        },
        {
          "day": "Friday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        },
        {
          "day": "Friday",
          "hourStart": 14,
          "minuteStart": 30,
          "hourEnd": 18,
          "minuteEnd": 0
        },
        {
          "day": "Saturday",
          "hourStart": 9,
          "minuteStart": 0,
          "hourEnd": 12,
          "minuteEnd": 30
        }
      ]
    },
    "created": 1475608861,
    "active": true
  },
  "responseType": "OK"
}

I guess @bereczandor needs to parse it in a different way. Happy to change the response if that it is too tricky on the ui side.

**Comment by bereczandor** [comment]
please change it in the backend and deliver the data grouped by day. frontend should have as little as possible calculations etc.
