### ISSUE TITLE
Bug - iPhone ViewPort Issue

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#18]
When I open the website on an iphone it appears zoomed out. I believe this is something to do with the Viewport in the header. Here is an example.

<meta name="viewport" content="width=device-width, initial-scale=1">

![iphone-screenshot](https://cloud.githubusercontent.com/assets/122441/19124784/e140032e-8b34-11e6-90b3-ad2f4cf17289.PNG)
#

**Comment by russog** [comment]
very weird, it works fine on mine (bear in mind I use chrome)

**Comment by corebean** [comment]
So weirdly this is still an issue on my old iPhone4S. 
I just uploaded a pure HTML solution (here: http://posthost.it/ladenfreude/) to test and the viewport displays fine. But when I go to the Zeroes Apps version everything appears small. 

The issue for now is that in order for us to present the concept, it should work at least on our device. Any ideas on how to solve?

**Comment by bereczandor** [comment]
solved. the old hosting provider changed the viewport automagically. on the new hosting seems to work
