### ISSUE TITLE
Image Size Limits

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#2]
Very large 7MB file uploaded. Example here http://ladenfreude.zeroesapps.com/post/101098

**Comment by russog** [comment]
should we have a limit to the upload?

**Comment by bereczandor** [comment]
When the crop feature will be enabled that will take care of the final image size(i guess :) )

**Comment by corebean** [comment]
An image upload limit might not be necessary, but we then need to show the
user a bar of how long it will take to upload. Nothing fancy for now, but
some sort of progress percentage would be good UX. Else we need just small
hint telling it will take a while if the file is large.
