### ISSUE TITLE
Change Request - Category Name

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#20]
Kate noticed that this German is incorrect.
"Veröffentliched in Gemisch" (it appears on the Post details page)

It should read
"Veröffentlicht in Verschiedenes".
This means the statis text "Veröffentlicht in" needs to be changed, but in the Category list, delete "Gemisch" and replace "Verschiedenes"

**Comment by bereczandor** [comment]
I have changed the wording. Its Giuseppee's task to change the category name.
