### ISSUE TITLE
Newsletter Page/Signup

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#22]
On the current home page is the "Abonnieren" button that only asks for an Email address. That was fine, but for marketing we need to capture "First name", "Last name", "Email" and "Postcode". 

Can the "Abonnieren" button the home page now please link to the "Newsletter" page. 

http://www.ladenfreu.de/newsletter/

**Comment by bereczandor** [comment]
Button links to Newsletter page
