### ISSUE TITLE
Newsletter Sign Up Code

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#23]
As discussed in Slack - please either capture the newsletter information into a DB and give me access to export, or use the following code so Campaign Monitor can capture information

Fields to capture:
- Vorname
- Nachname
- Email
- PLZ

Or the Campaign Monitor Code

<form action="http://corebean.createsend.com/t/r/s/ktzjkh/" method="post" id="subForm">
   <p>
       <label for="fieldtufudut">Vorname</label><br />
       <input id="fieldtufudut" name="cm-f-tufudut" type="text" />
   </p>
   <p>
       <label for="fieldtufudui">Nachname</label><br />
       <input id="fieldtufudui" name="cm-f-tufudui" type="text" />
   </p>
   <p>
       <label for="fieldEmail">Email</label><br />
       <input id="fieldEmail" name="cm-ktzjkh-ktzjkh" type="email" required />
   </p>
   <p>
       <label for="fieldtufuduj">PLZ</label><br />
       <input id="fieldtufuduj" name="cm-f-tufuduj" type="text" />
   </p>
   <p>
       <button type="submit">Subscribe</button>
   </p>
</form>

**Comment by bereczandor** [comment]
Your campaign does not accept any kind of email address
