### ISSUE TITLE
New Business - Add new business TOAS BIKES & MORE

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#27]
**Toa's Bikes & more**
Bahnhofstr. 40
64401 Groß-Bieberau
telefon: 06162 8164-0
mail: toa-s@t-online.de

**Öffnungszeiten**
Mo/Di/Do/Fr
9.00-12.30 u. 14.30-18.00 Uhr
Mittwoch
9.00-12.30 Uhr
Samstag
9.00-13.00 Uhr

Do I need to supply these above Opening Times (Öffnungszeiten) in English so you can add to Database easier?

**Comment by russog** [comment]
yes please in english......

**Comment by corebean** [comment]
Monday: 09:00-12:30 and 14:30-18:00
Tuesday: 09:00-12:30 and 14:30-18:00
Wednesday: 09:00-12:30
Thursday: 09:00-12:30 and 14:30-18:00
Friday: 09:00-12:30 and 14:30-18:00
Satruday 09:00-13:00 
Sunday: Closed

**Comment by russog** [comment]
I added it to the db.....I used google ;)

**Comment by corebean** [comment]
Sorry - but Wednesday and Thursday times are mixed up. Wednesday is only the half day, Thursday is the morning plus afternoon.

**Comment by russog** [comment]
@corebean could you check this is now fixed and if it is can you please close the ticket?
