### ISSUE TITLE
Portrait versus Landscape Images

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#3]
Very large 7MB file uploaded in Portrait mode appears to be uploaded in Landscape mode. See this post for example. http://ladenfreude.zeroesapps.com/post/101098

**Comment by bereczandor** [comment]
At the moment we just take the image in whatever format it is. We don't change anything. When the crop feature will be enabled, then the crop result will be landcape as well. If you do want portrait mode then you will have to adjust the CSS for the list, like sho only the top/middle part of an image, the rest should be overflow: hidden. I hope it makes sense

**Comment by corebean** [comment]
But this  was a bug I found. I uploaded the 7mb file in portrait mode and
it is being displayed in landscape mode.

**Comment by bereczandor** [comment]
f i take a portrait photo with my phone, it will be saved in landscape on my phone. if i use that image and upload it into a post, it will be uploaded as landscape, how it was saved from the camera on the phone.

**Comment by corebean** [comment]
Yes - I have shown this to Kathrin and shown her how to Edit photos before
uploading on the desktop. It is a problem on a mobile device, but we can
solve this later.

**Comment by corebean** [comment]
Am reopening this issue as I think I found a problem with the upload process. Please try it yourself, 1). Long/thin image was uploaded by the client and was continually uploaded on it's side
2). I tried editing/turning the image with Photoshop and re-uploading. No change.
3). Cropped the image to a square format and it worked.
We need to either have some text recommended image format or re-implement the upload image process with crop and other tools. For Mobile devices, I will suggest people download the free Snapseed (from Google) which can then be used to edit images, before uploading.

![1478862569975-1478608842-square](https://cloud.githubusercontent.com/assets/122441/20239280/4c606262-a8fd-11e6-858e-dbbdc75d90a8.jpg)
![1478862569975-1478608842](https://cloud.githubusercontent.com/assets/122441/20239281/4c631980-a8fd-11e6-9680-cbbb5ebc9516.jpg)

**Comment by bereczandor** [comment]
I have tested the following image 
ladenfreu.de/McMurdo_labeled-portrait.jpg

15 Mb large, portrait.

It succeded on CHrome and Firefox.

However, sometimes it fails to generate the preview on Firefox. This happens when my browser uses a lot of memory, or perhaps the PC has an old configuration. Thats something i canot control. The preview is happening on the client machine, if the machine can't pack it then bad luck..
