### ISSUE TITLE
Image Upload - Rotating Images

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#36]
Kathrin uploaded some images from the desktop, but they appear to have rotated (hochformat to querformat). Is there anyway to control this and/or edit if an image is uploaded incorrectly?

**Comment by bereczandor** [comment]
thats a native upload. but ill have a looks

**Comment by bereczandor** [comment]
desktop is not rotating the images. you can upload either landscape, either portrait images
