### ISSUE TITLE
Image Upload Issues

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#38]
Mobile Uploads from the Desktop (Firefox) just show the continually turning circle. Even after 20 minutes of waiting. Have tried twice with no upload completed.

iPhone4S (Safari) allows me to upload (it returns me to the Start page), but no upload is visible. If I got into "Beiträge" I can see the post is there, but the image is missing. 

Lets just focus on getting Image Upload to work on Desktop without error and ignore mobile uploads for now. Kate wants to show client tomorrow and they will only use it on a Desktop.

**Comment by bereczandor** [comment]
try to logout/login, refresh the page and it should work
