### ISSUE TITLE
Post Display Problem

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#39]
So a new client uploaded a test item today and managed to get content to display that I didn't know existed. If you check out the post "http://ladenfreude.zeroesapps.com/post/101135" you can see the numbers "1477587527" appear above the Title. But no where in the Edit Post section can this content be found to update.

Interestingly though on this page this information is NOT displayed "http://ladenfreude.zeroesapps.com/my-posts".

**Comment by bereczandor** [comment]
the numbers are a date. the user is missing the company and javascript failed to go further with the page..so it displayed just the numbers..

date is displayed now but no company there
