### ISSUE TITLE
Edit Post - Category Issue

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#41]
After a post has been uploaded, there appears to be no way to edit the Category.

1. On the Beiträge page (Post Overview), you have a dropdown list with the current category, but no more options appears.
2. If you click on "Editieren", you are taken to the Post Edit page, but there is no Category dropdown list appearing

**Comment by bereczandor** [comment]
As per Kate's request the category edit has been disabled in Edit mode

**Comment by corebean** [comment]
Okay - this I don't understand. I'll need to look through the text she
supplied, but removing the ability to edit the Category in Edit mode makes
no sense. All fields should be editable.

I am sorry for the doubling of your work, but it will need to be made
available to change Categories in Edit Mode.

**Comment by bereczandor** [comment]
WIth the next build will be available
