### ISSUE TITLE
Edit Post - Activate/Deactivate Issue

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#42]
On the "Beiträge" page (Posts Overview), there are buttons to "Aktivieren/Deaktivieren" for the post, but when you set it to deactivate, there is no saving of the setting in background, or a button to submit changes. This option is also not available in the "Editieren" page.

**Comment by bereczandor** [comment]
When you activate/deactivate a post, o the list, the button text do changes. So when you click Deactivate, the button will become Activate. We canot add a button to submit the changes, that doesn't make any sense in our case. 

There is one option to achieve what you want. Checkboxes. We add checkboxes next to the post, they will be checked and there will be an action button to be carried out with the marked posts. But again, for that you need a regular vertical list.

As UI/UX point of view, it is much faster to do one click on an entry to activate/deactivate it. People do need to learn how the system work. It's like that everywhere.

Please decide how do you want it so we can close the issue.

**Comment by bereczandor** [comment]
The same for the Activate/Deactivate from the post-edit page. If you want to keep the page simple, you would leave the Active field out of it, as it is now. If someone do wants to add a deactivated post, they can do that by adding a post and clicking deactivate on the list.

Let me know if you want the active field in the Post detail page.

**Comment by corebean** [comment]
Leave it the way it is. You are right, this is unnecessary work right now
and I am sure users will give us better feedback as we go along. Just close
it for now and we can see how users go with giving us feedback.
