### ISSUE TITLE
Delete / "Löschen" Post - Change request

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#43]
Currently the "Löschen" button the "Beiträge" page works intermittently. For example on the page for the "Ladenfreu.de" Account, I have one post there called "Facebook Post Upload" and I cannot delete it. I have logged out and back in. Issue is happening on Firefox on a Desktop.

Could you please also add a simple Javascript popup message that asks someone to confirm they want to delete the Post? This helps with usability in the event the button is accidentally clicked. At a later date allowing the user to recall or undo a delete would also be awesome. If you need text for the Popup - please use this "Möchtest du den Beitrag wirklich löschen?". The two buttons on the pop-up would say "Ja" (yes) and "Rückgängig machen" (close window).

**Comment by bereczandor** [comment]
making an undo to a deleted post bring us a lot of work. we will need a deleted posts section then..that will be confusing.

**Comment by bereczandor** [comment]
i canot have the yes/no for confirm dialog changed. those are standard texts. if it were to build such a component, it takes at least 8 hours of work

**Comment by bereczandor** [comment]
i deleted your facebook post with 1 click. sorry, but i canot imagine how that would'nt work...and worked for others.

**Comment by bereczandor** [comment]
confirm available with the next update.
