### ISSUE TITLE
Page Text Update

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#45]
Two pages have text that needs to be edited. One is the "Hochladen" (Upload/Beitrag) page and the other is the "Beitrag bearbeiten" (Edit) page. 

http://www.ladenfreu.de/my-posts/add
Page titel "Beitrag erstellen" +  Description text "Hier kannst du die Anzeige erstellen und live setzen"

http://www.ladenfreu.de/my-posts/edit/
Description text "Hier kannst du den Inhalt der Anzeige verändern"

**Comment by bereczandor** [comment]
will be live with the next build
