### ISSUE TITLE
FAQs Page - Updates to the content

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#47]
On the FAQs page, there is some text describing functionality that doesn't exist yet. We need to remove it until it's available, so for now, please replace only the first paragraph with the following:

**Wie funktioniert’s?**
Unsere Plattform gibt Ladenbesitzern die Möglichkeit, Informationen zu ihren Produkten, Diensten und Läden hochzuladen. Stellt Euch vor, Ihr bekommt die Infos über Angebote der Woche nicht wie üblich (nur) in Form von einem Stapel Prospekte (z. B. Rewe, Aldi, Lidl, etc) sondern stattdessen angezeigt auf der Webseite und/-oder Smartphone. 

Below that under the heading "Wie kann ich mich registieren?" the hyperlinking page is incorrect for the text the ends with "...kostenfreien newsletter registrierst." Currently the "registrierst" takes the person to the home page of Ladenfreude, but instead should point to the "Newsletter" page.

**Comment by corebean** [comment]
Corbin and Kate are actually re-working this page/content. Please ignore update request until we supply new information

**Comment by bereczandor** [comment]
- have made anyway the changes. will be available with the next build

**Comment by corebean** [comment]
Andor - sorry - maybe it wasn't clear - but in the comment afterward, I asked this be put on hold. I've worked on the layout/content today and wanted to supply a new Über Uns page. And later this week will be including the new FAQs page.

**Comment by bereczandor** [comment]
yes, you were clear, but as i already opened the file i did the changes.
having so many open issues you don't know from where to start, so i want to close them all! :)

**Comment by corebean** [comment]
Vielen dank Andor - ich schätze deine Hilfe sehr.
