### ISSUE TITLE
Newsletter Redirect

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#49]
So this problem we had before, but since the move to the new domain, the Newsletter Signup page is throwing up a message about the email being incorrect. Andor - perhaps you remember we had this whilst hosting on zeroesapps server and you did something to update/change Angular to accept the email account?

![newsletter-screenshot](https://cloud.githubusercontent.com/assets/122441/19832693/1e83c780-9e2b-11e6-8b63-b58ba9fa9aab.png)

**Comment by corebean** [comment]
Again - if we prefer to setup a Database on the server to capture people's details who sign up, I am happy to do that. I just however need to ensure once I hand out these printed flyers encouraging people to sign up to the newsletter that it all works.

**Comment by bereczandor** [comment]
no, i did not change anything at the code. as i remember this still was on the todo list. but ill have a look now.

**Comment by bereczandor** [comment]
nope, i cant figure it out why it doens't work.

there is one issue with your form, the landing page link should point to 
newsletter/enewsletter-bestatigung
instead of enewsletter/enewsletter-bestatigung

**Comment by bereczandor** [comment]
done and live, please fix the success landing page
