### ISSUE TITLE
Posts Issue - Example Wollboutique

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#51]
It appears something has happened with Posts and the Categories they are assigned to.

This example is for the 4x Posts for the company "Wollboutique", but you can see this for all other businesses. Here are the problems
1). All posts upload date are set to today (1/11/2016)
2). The post's Categories (when viewing from within the "Meine Beiträge" page) appear to be duplicated in the drop-down list
3). Even if you Edit the post and change the category it won't save and instead returns the following error:

`Response with status: 200 OK for URL: http://api.ladenfreude.zeroesapps.com/posts`

This appears to be affecting all the businesses/accounts.

**Comment by bereczandor** [comment]
category can be saved now.
