### ISSUE TITLE
Error Message on Saving Posts

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#52]
Now I am trying to edit new posts created today and getting the same error code Kate registered earlier.

`Response with status: 200 OK for URL: http://api.ladenfreude.zeroesapps.com/posts`

**Comment by corebean** [comment]
Sorry - closed by mistake as part of the problem has resolved itself. But I am still getting this response code

**Comment by bereczandor** [comment]
code removed, but the other issues cannot be reproduced.
