### ISSUE TITLE
Page Wie Funktioniert's - New Page

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#60]
Another page has been created with text content, layout and images. I have already created all the HTML/CSS and necessary stuff for the page update. Just let me know how you need it.

![screenshot-wiefunktioniert](https://cloud.githubusercontent.com/assets/122441/20041016/94a8ddc8-a462-11e6-96e3-cecf01a29a1f.png)

**Comment by bereczandor** [comment]
HTML/CSS/Images would be perfect. Setup a page from the templates add make a new css file. Then i can simply copy over the css and the content.

**Comment by bereczandor** [comment]
The same for every new page/page layout change. If you can do the HTML/Css part on a template, that would be great. Perhaps we can find some time to install angular on your mac..

**Comment by corebean** [comment]
Wann ich die CSS in der Header (also zwischen <style></style>) in ein HTML Datei und dann die IMGs als .ZIP hochladen, wäre das okay?

**Comment by bereczandor** [comment]
ja, das wäre OK.

**Comment by corebean** [comment]
Also - dann hier sind alle 3x Seiten + ein Image .ZIP Datei.


[pages.zip](https://github.com/zeroesapps/ladenfreude/files/574108/pages.zip)

[img-upload.zip](https://github.com/zeroesapps/ladenfreude/files/574107/img-upload.zip)
