### ISSUE TITLE
Newsletter Success Page

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#62]
Due to the stupid lawyers in Germany, we require a two-step confirmation for newsletter on Ladenfreude. This means I simply need the following URL path to have a page setup with the text found in the HTML file within the .ZIP (attached - but the page is very similar to the FAQs page).

**http://www.ladenfreu.de/newsletter/enewsletter-erfolg**

[enewsletter-erfolg.html.zip](https://github.com/zeroesapps/ladenfreude/files/576588/enewsletter-erfolg.html.zip)

**Comment by corebean** [comment]
I forgot to mention that the following code will need to replace the current Newsletter sign up form. Can you please replace the necessary fields so it works?

**Comment by bereczandor** [comment]
i don't get it..what you sent me was a text page. please explain the whole signup-confirm-thank you pages stuff, i am lost.

**Comment by corebean** [comment]
Sorry - I pasted code from Campaign Monitor but it's been converted to just text. Hang on.

**Comment by corebean** [comment]
`<form action="http://corebean.createsend.com/t/r/s/khlyoi/" method="post" id="subForm">
    <p>
        <label for="fieldidkhdrkr">Vorname</label><br />
        <input id="fieldidkhdrkr" name="cm-f-idkhdrkr" type="text" />
    </p>
    <p>
        <label for="fieldidkhdyz">Nachname</label><br />
        <input id="fieldidkhdyz" name="cm-f-idkhdyz" type="text" />
    </p>
    <p>
        <label for="fieldEmail">Email</label><br />
        <input id="fieldEmail" name="cm-khlyoi-khlyoi" type="email" required />
    </p>
    <p>
        <label for="fieldidkhdyhl">PLZ</label><br />
        <input id="fieldidkhdyhl" name="cm-f-idkhdyhl" type="text" />
    </p>
    <p>
        <button type="submit">Subscribe</button>
    </p>
</form>`

**Comment by corebean** [comment]
Better?
